// jsPDF is dynamically imported inside downloadInvoicePdf so the ~400KB
// PDF library never enters the main bundle — only loaded when an invoice
// is actually downloaded.

export type InvoiceData = {
  invoice_number: string;
  issued_at: string;
  subtotal: number;
  vat_percent: number;
  vat_amount: number;
  total: number;
  currency: string;
  // Order
  package_name: string;
  credits: number;
  payment_method: string;
  transaction_id?: string | null;
  order_id: string;
  // Customer
  customer_name: string;
  customer_email: string;
  // Site
  site_name: string;
  site_logo_url?: string;
  contact_email?: string;
  contact_phone?: string;
};

const money = (n: number, c: string) => `${c === "BDT" ? "৳" : c + " "}${Number(n).toFixed(2)}`;

// Generate a clean A4 PDF invoice and trigger browser download.
export const downloadInvoicePdf = async (d: InvoiceData) => {
  const { default: jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const M = 48;
  let y = M;

  // Header band
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, W, 90, "F");
  doc.setTextColor(255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(d.site_name || "Invoice", M, 50);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  if (d.contact_email) doc.text(d.contact_email, M, 68);
  if (d.contact_phone) doc.text(d.contact_phone, M, 82);

  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("INVOICE", W - M, 50, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`# ${d.invoice_number}`, W - M, 68, { align: "right" });
  doc.text(new Date(d.issued_at).toLocaleString(), W - M, 82, { align: "right" });

  y = 130;
  doc.setTextColor(15, 23, 42);

  // Bill to
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text("Bill to", M, y);
  doc.setFont("helvetica", "normal");
  doc.text(d.customer_name || "Customer", M, y + 16);
  doc.text(d.customer_email || "", M, y + 30);

  // Order meta
  doc.setFont("helvetica", "bold");
  doc.text("Order", W - M - 200, y);
  doc.setFont("helvetica", "normal");
  doc.text(`ID: ${d.order_id.slice(0, 8)}…`, W - M - 200, y + 16);
  doc.text(`Method: ${d.payment_method}`, W - M - 200, y + 30);
  if (d.transaction_id) doc.text(`Txn: ${d.transaction_id}`, W - M - 200, y + 44);

  y += 80;

  // Table header
  doc.setFillColor(241, 245, 249);
  doc.rect(M, y, W - M * 2, 26, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Description", M + 12, y + 17);
  doc.text("Qty", W - M - 200, y + 17);
  doc.text("Amount", W - M - 12, y + 17, { align: "right" });

  y += 26;
  doc.setFont("helvetica", "normal");
  doc.text(`${d.package_name} (${d.credits} credits)`, M + 12, y + 18);
  doc.text(String(d.credits), W - M - 200, y + 18);
  doc.text(money(d.subtotal, d.currency), W - M - 12, y + 18, { align: "right" });
  y += 36;

  doc.setDrawColor(226, 232, 240);
  doc.line(M, y, W - M, y);
  y += 14;

  // Totals
  const tx = W - M - 200;
  const ax = W - M - 12;
  doc.text("Subtotal", tx, y);
  doc.text(money(d.subtotal, d.currency), ax, y, { align: "right" });
  y += 18;
  doc.text(`VAT (${d.vat_percent}%)`, tx, y);
  doc.text(money(d.vat_amount, d.currency), ax, y, { align: "right" });
  y += 22;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Total", tx, y);
  doc.text(money(d.total, d.currency), ax, y, { align: "right" });

  // Footer
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text(
    `Thank you for your purchase. Generated by ${d.site_name}.`,
    W / 2,
    doc.internal.pageSize.getHeight() - 30,
    { align: "center" }
  );

  doc.save(`${d.invoice_number}.pdf`);
};
