// Stubbed: this file is auto-regenerated by the platform for TanStack Start
// templates, but this project uses React Router + Vite and never imports it.
// We replace the regenerated body with a no-op so the missing
// `@tanstack/react-start` package doesn't break the build.
export const requireSupabaseAuth = undefined as unknown as never;
