// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iezlqsacshgxlgptqwhe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imllemxxc2Fjc2hneGxncHRxd2hlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY3MDc4NzQsImV4cCI6MjA5MjI4Mzg3NH0.g53boZ9vCuWjk_FJHUOu0z4bXraho9NVy-KlJ0D1HVg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});